### ISSUE TITLE
”musicgen-small“  the path to the model file？

### ISSUE THREAD

**Issue by aimarxjg** [gabotechs/MusicGPT#11]
Hello, I downloaded the WIN version, it automatically downloads the musicgen-small model file, in the C drive letter in what folder? What is the file name? I searched "musicgen" and couldn't find it

**Comment by gabotechs** [comment]
In windows, all the files that the app might download land in
```
C:\Users\Your User\AppData\Roaming\gabotechs\musicgpt\data
```

**Comment by aimarxjg** [comment]
thx~
