### ISSUE TITLE
Where are the models stored?

### ISSUE THREAD

**Issue by Elwag** [gabotechs/MusicGPT#16]
Hi,
I installed musicgpt and downloaded some models, but I can't determine where the models are stored.
My main drive is now full and I would really like to delete those models and put them somewhere else.

1. Where are the models so I can delete them?
2. Can I reroute musicgpt to put the models somewhere else?

Thanks!

**Comment by gabotechs** [comment]
Windows: `C:\Users\Your User\AppData\Roaming\gabotechs\musicgpt`
MacOS: `/Users/Your\ User/Library/Application\ Support/com.gabotechs.musicgpt`
Linux: `/home/Your \User/.config/muscigpt`

I'll add it to the readme as this has already been asked before

**Comment by Elwag** [comment]
Thank you so much!
I don't think I'm the only person who benefits from this👍

**Comment by pyramid3d** [comment]
Just want to add that for some reason on Arch Linux the data folder is set by default to (using the precompiled binary)
~/.local/share/musicgpt
